### PR TITLE
Mail recruitment

### PR DESCRIPTION
**Pull request by EliHaugu**
Added mail support for deleted admissions :)

Resolves ABA-192

### CODE REVIEW

**Comment by EliHaugu** [comment]
Don't know why the poetry.lock file is so changed, and need to squash later (have to run to bus right now!!!)

**Comment by EliHaugu** [comment]
image
also for some reason looks like this on hotmail idk why

**Review by norbye — APPROVED** [review]
LGTM:) Awesome stuff(:

**Comment by norbye** [comment]
> also for some reason looks like this on hotmail idk why

I don't think this should be that big of a problem. As far as I can tell we only store the Abakus-email (if it exists for the user), so as long as it looks fine in gmail that should be enough.

**Review by LudvigHz — APPROVED** [review]
LGTM

**Comment by EliHaugu** [comment]
can someone double check that this works after merging with the slug things? :D

**Comment by norbye** [comment]
Resolved in #1288

**Pull request closed without merging**
